# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://battlelinesdrawn.com/"  # Include trailing slash
copyright = "Jack Hughes"
paginate = 10
theme = ["github.com/chipzoller/hugo-clarity"]
disqusShortname = ""
DefaultContentLanguage = "en"
enableGitInfo = false
enableRobotsTXT = true

# There are no categories or series as yet 
[taxonomies]
  tag = "tags"
  army = "armies"
  project = "projects"
  supplier = "suppliers"
  ruleset = "rulesets"

[outputs]
  home = ["HTML", "RSS", "JSON"]
